#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calc.Resource", IsApplication=true)]

namespace Calc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_next = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_prev = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CalcIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001a
			public const int Button0 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int Button1 = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int Button2 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Button3 = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int Button4 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Button5 = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int Button6 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Button7 = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int Button8 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Button9 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int ButtonAdd = 2131034124;
			
			// aapt resource value: 0x7f050019
			public const int ButtonBackspace = 2131034137;
			
			// aapt resource value: 0x7f050009
			public const int ButtonC = 2131034121;
			
			// aapt resource value: 0x7f05001c
			public const int ButtonComma = 2131034140;
			
			// aapt resource value: 0x7f050011
			public const int ButtonDiv = 2131034129;
			
			// aapt resource value: 0x7f05001d
			public const int ButtonEqual = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int ButtonFraction = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int ButtonMC = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ButtonMR = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ButtonMS = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int ButtonMulti = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int ButtonNegate = 2131034136;
			
			// aapt resource value: 0x7f050014
			public const int ButtonSqrt = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int ButtonSub = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int Layout = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TextView = 2131034113;
			
			// aapt resource value: 0x7f050023
			public const int acos = 2131034147;
			
			// aapt resource value: 0x7f050027
			public const int actg = 2131034151;
			
			// aapt resource value: 0x7f050021
			public const int asin = 2131034145;
			
			// aapt resource value: 0x7f050025
			public const int atan = 2131034149;
			
			// aapt resource value: 0x7f050004
			public const int calcView1 = 2131034116;
			
			// aapt resource value: 0x7f05001e
			public const int calcView2 = 2131034142;
			
			// aapt resource value: 0x7f050022
			public const int cos = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int ctg = 2131034150;
			
			// aapt resource value: 0x7f05002f
			public const int div = 2131034159;
			
			// aapt resource value: 0x7f05002b
			public const int exp = 2131034155;
			
			// aapt resource value: 0x7f050005
			public const int functions = 2131034117;
			
			// aapt resource value: 0x7f050028
			public const int ln = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int log = 2131034153;
			
			// aapt resource value: 0x7f05002e
			public const int mod = 2131034158;
			
			// aapt resource value: 0x7f05002a
			public const int pi = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public const int pov = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int rand = 2131034157;
			
			// aapt resource value: 0x7f050020
			public const int sin = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int standart = 2131034143;
			
			// aapt resource value: 0x7f050024
			public const int tan = 2131034148;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int viewSwitcher = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calcTab = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int convertTab = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
