#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calc.Resource", IsApplication=true)]

namespace Calc
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int Button0 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Button1 = 2131034135;
			
			// aapt resource value: 0x7f050012
			public const int Button2 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Button3 = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int Button4 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Button5 = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int Button6 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Button7 = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int Button8 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Button9 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ButtonAdd = 2131034120;
			
			// aapt resource value: 0x7f050015
			public const int ButtonBackspace = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int ButtonC = 2131034117;
			
			// aapt resource value: 0x7f050018
			public const int ButtonComma = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int ButtonDiv = 2131034125;
			
			// aapt resource value: 0x7f050019
			public const int ButtonEqual = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int ButtonFraction = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int ButtonMC = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ButtonMR = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ButtonMS = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int ButtonMulti = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int ButtonNegate = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int ButtonSqrt = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int ButtonSub = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int ResultField = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int TextView = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
